로비 페이지 구현
GunBros/ReactPracticeToy pull request #12
Opened 2023-07-29 09:10 UTC by PoLyBear2

### 11

    #11 

### 개요(간단한 작업 내용 설명)
로비 페이지 구현
- 방 정보 확인 가능
- 티어 별 태그 색상이 다름을 확인 가능
### 스크린 샷 및 화면(뷰 개발시 필수)사용 예시 - Front
![image](https://github.com/GunBros/ReactPracticeToy/assets/109647226/20204049-4a6a-4dbb-a194-f09be4080f48)

2023-07-30 09:14 UTC, GunBros requested changes

2023-07-30 09:14 UTC, GunBros commented on PoLyBear2/react-toy/src/hooks/useTierColor.jsx
> +    const [tierColorClass, setTierColorClass] = useState('');
(질문) 방의 색상을 상태로 분리한 이유가 있을까요?

2023-07-30 09:14 UTC, GunBros commented on PoLyBear2/react-toy/src/components/Login.jsx
로비페이지를 구현하는데 해당 컴포넌트에서 왜 수정이 일어난 이유가 궁금해요

2023-07-30 09:14 UTC, GunBros commented on PoLyBear2/react-toy/src/components/Login.jsx
> +    return (
하나의 컴포넌트가 너무 많은  View를 담당하고 있어서  각각의 역할은 무엇인지 무엇을 구현하고 있는지 전혀 모르겠어요.  컴포넌트를 분리해보는건 어떨까요?

2023-07-30 09:14 UTC, GunBros commented on PoLyBear2/react-toy/src/components/card/Roomcard.jsx
> +    return (
이 부분도 위 Login과 마찬가지로 무엇을 구현하고 있는지 모르겠어요. 컴포넌트를 분리해주세요!

2023-07-30 09:16 UTC, GunBros commented
커밋 컨벤션, PR 컨벤션이 지켜지지 않았어요. 팀 깃 컨벤션을 다시 확인해주세요.

하나의 커밋에 모든 작업 사항이 반영되어 있어서 리뷰를 하는 데에도 어려움이 많네요.  작업 단위로 커밋을 해보는건 어떠락요? 로비 페이지 구현인데 login 컴포넌트에 수정이 왜 일어났는지도 알 수가 없어요.

2023-07-30 09:18 UTC, GunBros commented
프로젝트에 불필요한 폴더(.idea)가 같이 포함이 된 것 같은데 이부분도 해결해주세요!

2023-07-30 09:25 UTC, GunBros commented
명세서에 티어에 따른 색상도 지정해두어서 방의 색상도 변경 부탁드리겠습니다!

2023-07-31 00:48 UTC, PoLyBear2 commented on PoLyBear2/react-toy/src/hooks/useTierColor.jsx
> +    const [tierColorClass, setTierColorClass] = useState('');
커스텀 훅을 작성해 보고 싶어서 구현 해 보았습니다. state 없이 useEffect에서 return 하는 방식을 써보다가 잘 안되서 틀었어요

2023-07-31 01:03 UTC, GunBros commented on PoLyBear2/react-toy/src/hooks/useTierColor.jsx
> +    const [tierColorClass, setTierColorClass] = useState('');
로직을 별도로 분리하여 커스텀 훅으로 작성해보는 시도는 매우 좋았다고 생각해요 👍
하지만 방의 색상은 한번 결정이 되면 변하지 않으므로 state로 분리하지 않는 것이 맞다고 생각하기 때문에 다른 방법을 찾아보는게 좋을 것 같아요!

2023-07-31 01:33 UTC, PoLyBear2 commented
### 수정 내용
 - 방 상세 페이지 작업을 위해 Roomcard.jsx navigate 추가
 - '/hooks/useTierColor.jsx' state 삭제
 - login.jsx 추후 다른 issue로 수정 예정
 - 색상은 tailwindcss 에서 제공하는 색상이 조금 다르므로 추후 다른 style issue에서 수정 예정

2023-07-31 03:11 UTC, GunBros commented on PoLyBear2/react-toy/src/hooks/useTierColor.jsx
>  const useTierColor = (tier) => {
사용되지 않는 함수는 제거해주세요.

2023-07-31 03:13 UTC, GunBros commented
이슈번호는 대괄호로 감싸야하고 커밋에는 타입을 작성해주어야해요. [깃 컨벤션](https://www.notion.so/Git-22ae3d511a9249e3b3741de467274972?pvs=4)을 다시 확인해주세요!

별도의 이슈로 처리해야하는 부분은 바로 이슈로 생성해주세요.

2023-07-31 03:14 UTC, GunBros requested changes

2023-07-31 03:14 UTC, GunBros commented on PoLyBear2/react-toy/src/hooks/useTierColor.jsx
> +const useTierColor = (tier) => {
사용되지 않는 함수는 제거해주세요.

2023-07-31 03:18 UTC, PoLyBear2 commented
### 수정 내용
 - 미사용 함수 제거

2023-07-31 05:27 UTC, merged