[4] feat: 로그인 성공 시 rooms 로 이동, 로그인 실패시 경고
GunBros/ReactPracticeToy pull request #15
Opened 2023-07-30 04:23 UTC by Manna-na

### 이슈번호
#4 

### 개요(간단한 작업 내용 설명)

이메일 주소와 비밀번호의 일치 여부를 파악하여 로그인 기능을 수행한다.

### 스크린 샷 및 화면(뷰 개발시 필수)사용 예시 - Front
- 로그인 화면
 ![image](https://github.com/GunBros/ReactPracticeToy/assets/123603435/63aafa18-180c-4bab-9d8b-5606d470743a)

- 로그인 실패 시 화면 경고
 ![image](https://github.com/GunBros/ReactPracticeToy/assets/123603435/e90b793c-e1e6-48a2-9c64-697bfb4b2719)

- 로그인 성공 시 /rooms로 이동
 ![image](https://github.com/GunBros/ReactPracticeToy/assets/123603435/4ade7b36-de11-42a7-b5f4-d774ccb923ea)

### 작업한 내용
6030c26a43d7172118245d4f0de11edb2f2afc75 - [[4] feat: 로그인 성공 시 rooms 로 이동, 로그인 실패시 경고]

2023-07-30 09:22 UTC, GunBros requested changes

2023-07-30 09:22 UTC, GunBros commented on Hanna Kim/react-toypj/src/components/login/loginForm.js
> +    async function logJSONData() {
`logJSONData`라는 함수명은 어떤 기능을 담당하는지 잘 와닿지 않는 것 같아요. 사용자의 데이터를 가져오는 함수 같은데 기능과 관련된 함수명으로 바꾸는게 좋을 것 같아요!

2023-07-30 09:22 UTC, GunBros commented on Hanna Kim/react-toypj/src/components/login/loginForm.js
> +  return (
해당 컴포넌트에서 로그인 페이지를 다 구현하고 있는 것 같애요.  로그인 페이지에 포함되어 있는 View들을 컴포넌트 별로 분리해보는건 어떨까요?

2023-07-30 09:23 UTC, GunBros commented
PR 컨벤션, 커밋 컨벤션 모두 잘 지켜주셨어요 👍 로그인 페이지에 포함되어 있는 컴포넌트만 분리해주시면 좋을 것 같아요. 고생하셨습니다!

2023-07-30 23:40 UTC, Manna-na commented on Hanna Kim/react-toypj/src/components/login/loginForm.js
> +  return (
828cc77ee35508916ece7fed0620aaee71868f5d - View 별로 컴포넌트 분리 완료 했습니다.😊

2023-07-30 23:46 UTC, GunBros approved these changes
loginForm 파일명만 수정하시고 Merge 진행해주세요~

2023-07-30 23:46 UTC, GunBros commented on Hanna Kim/react-toypj/src/components/login/loginForm.js
컴포넌트명은 파스칼 케이스로 변경해주세요!

2023-07-30 23:46 UTC, GunBros commented on Hanna Kim/react-toypj/src/components/login/loginForm.js
> +    async function fetchUserData() {
👍

2023-07-31 00:05 UTC, Manna-na commented on Hanna Kim/react-toypj/src/components/login/loginForm.js
da31929fc913b0ad5d4f10a01f2edcb324ae3d66 - 완료했습니다😊

2023-07-31 00:07 UTC, merged